  USE ROLE ACCOUNTADMIN;
  
  SHOW API INTEGRATIONS;
  
  SHOW GIT REPOSITORIES;

  SHOW SECRETS;
  
  CREATE SECRET TASTY_BYTES_DEMO.DEV.GIT_PAT_SECRET
  TYPE = PASSWORD
  USERNAME = 'xavizone'
  PASSWORD = 'github_pat_xxxxx';


  DESCRIBE INTEGRATION MY_GIT_API_INTEGRATION;

  ALTER API INTEGRATION MY_GIT_API_INTEGRATION
  SET ALLOWED_AUTHENTICATION_SECRETS = (TASTY_BYTES_DEMO.DEV.GIT_PAT_SECRET);

  ALTER GIT REPOSITORY TASTY_BYTES_DEMO.DEV.PANEL_DEMO_GIT
  SET GIT_CREDENTIALS = TASTY_BYTES_DEMO.DEV.GIT_PAT_SECRET;

