ALTER USER xavizone 
SET RSA_PUBLIC_KEY='MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3cRwQtwoHb360KKujIUr
PKlosupED/eDxJ4xhuY9UtLOu66l378MvTHSIxSMNDgkRXJbLikYLO8ldF8aPpm3
OfYmHx6n95YpYDeSwYgzFoaTEEXOczCuW4bIfWA/t6dRkzxccqVvz373KHtJwHHT
wKz1dvTfjDj/uGqbfvmLaGkXrbNkscxufFtiBSYyAv01T+4OjU1NkYFdbrbVylPO
b9FouNbKG69/FjFGLFuhk/giGMaM3OfhiQHJM3w1/EdHbPglMD8Yjbcoj8w1WqPv
jFub32dP/qmT85hxrj2dzTQ2K7dR9gqMgwwMNmt9QSxKuctfoat0xqbHjmQ+0LJH
uQIDAQAB';

USE ROLE ACCOUNTADMIN;
CREATE DATABASE IF NOT EXISTS SNOWPIPE_STREAMING;
USE SCHEMA SNOWPIPE_STREAMING.PUBLIC;

create or replace table 
STREAMING_MYSQL_TO_SNOW as (
    SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.STORE_SALES LIMIT 1
    );
select count(*) from streaming_mysql_to_snow;