CREATE DATABASE IF NOT EXISTS PACKAGE_REPO_DB;
CREATE SCHEMA IF NOT EXISTS PACKAGE_REPO_DB.PYPI;

CREATE OR REPLACE ARTIFACT REPOSITORY PACKAGE_REPO_DB.PYPI.PYPI_REPO
  TYPE = PYPI;

  SELECT * FROM INFORMATION_SCHEMA.PACKAGES 
WHERE PACKAGE_NAME = 'faker' AND LANGUAGE = 'python';

USE ROLE ACCOUNTADMIN;
GRANT DATABASE ROLE SNOWFLAKE.PYPI_REPOSITORY_USER TO ROLE PUBLIC

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION pypi_access_integration
  ALLOWED_NETWORK_RULES = (snowflake.external_access.pypi_rule)
  ENABLED = true;